services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '5173:5173'
      - '9229:9229'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    depends_on:
      - mysql
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3001:3000'
    volumes:
      - ./backend:/app
      - /app/tmp
      - /app/log
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=mysql
      - DATABASE_USERNAME=todo_user
      - DATABASE_PASSWORD=todo_password
      - DATABASE_NAME=todo_development
    depends_on:
      - mysql
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8.0.43
    container_name: todo-mysql
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_development
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
      TZ: Asia/Tokyo
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone='+09:00'
    restart: unless-stopped

  test:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run test
    profiles:
      - test

  e2e:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run test:e2e
    profiles:
      - e2e
    depends_on:
      - app

volumes:
  mysql_data:
    driver: local
